# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56d2df728b69f4f57b0e56aefb22699ac0ad3c7a352fec426db0d88d95ba86ae05c648c79e9d2613d70bd71d1f8ce327eeb4881f950b6675a9162c39e41ce018

test:
  secret_key_base: 833e8447410fb85d3cf995393fddf2d0fbb72abb90516bd8a183db7aebd8316192676c9511295bd79d5f56ac2e2b720827f3e0339c4c2ed1e4262791528b9bf3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
